---
version: '3.8'

# Build and push with: -
#
# IMAGE_TAG=1.0.1 docker-compose build
# IMAGE_TAG=1.0.1 docker-compose push

services:
  job:
    build:
      context: .
      dockerfile: Dockerfile
    image: informaticsmatters/job-template:${IMAGE_TAG:-1.0.0}
